name: first_action

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout-repo
          uses: actions/checkout@v4
        - name: welcome message
          run: echo "Welcome to GitHub Actions"
        
        - name: List all files
          run: ls -ltra

        - name: Read Files
          run: cat README.md

        - name: Executing shell scripts
          run: |
            chmod +x .github/workflows/shell-script.sh
            .github/workflows/shell-script.sh