name: mulitple-jobs

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Installing Cowsay Programm
              run: sudo apt-get install cowsay -y
            - name: Executing Cowsay CMD
              run: cowsay -f dragon "RUN in Cover, I AM DRAGON .... " >> dragon.txt
            - name: Sleep for 10 seconds
              run: sleep 10
            - name: Upload dragon.txt file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-txt-file
                path: dragon.txt

    job_2:
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            - name: Installing Cowsay Programm
              run: sudo apt-get install cowsay -y
            - name: Executing Cowsay CMD
              run: cowsay -f dragon "RUN in Cover, I AM DRAGON .... " >> dragon.txt
            - name: Download dragon.txt file
              uses: actions/download-artifact@v4
              with:
                name: dragon-txt-file
    job_3:
        runs-on: ubuntu-latest
        needs: [job_1, job_2]
        steps:
            - name: Reading dragon.txt file 
              run: sudo apt-get install cowsay -y
            - name: Executing Cowsay CMD
              run: cowsay -f dragon "RUN in Cover, I AM DRAGON .... " >> dragon.txt
            - name: Download dragon.txt file
              uses: actions/download-artifact@v4
              with:
                name: dragon-txt-file
            - name: Reading file
              run: cat dragon.txt