name: mulitple-jobs

on: push

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Installing Cowsay Programm
              run: sudo apt-get install cowsay -y
            - name: Executing Cowsay CMD
              run: cowsay -f dragon "RUN in Cover, I AM DRAGON .... " >> dragon.txt
            - name: Sleep for 10 seconds
              run: sleep 10
            - name: Upload dragon.txt file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-txt-file
                path: dragon.txt

    # job_2:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Installing Cowsay Programm
    #           run: sudo apt-get install cowsay -y
    #         - name: Executing Cowsay CMD
    #           run: cowsay -f dragon "RUN in Cover, I AM DRAGON .... " >> dragon.txt
    #         - name: Sleep for 10 seconds
    #           run: sleep 10